### ISSUE TITLE
Crearea unei liste de discuții

### ISSUE THREAD

**Issue by cipriancraciun** [timisoara-business-venturers/meta#2]
## Concluzie

Pentru moment am ales utilizarea Google Groups:
* Google Group: https://groups.google.com/forum/#!forum/timisoara-business-venturers/join
* pagina de wiki aferentă: https://github.com/timisoara-business-venturers/meta/wiki/Lista-de-discutii

Observații:
* **toate mesajele sunt publice si vor fi arhivate;**
* lista de discuții poate fi folosită fie via email, sau via interfața web;
* nu necesita crearea unui cont de Google;  este suficientă o adresă de email validă (indiferent de provider);
* interfața web poate fi folosită doar cu un cont de Google;
* oricine poate să se înscrie;

**Comment by mblaje** [comment]
@cipriancraciun crezi ca am incheiat acest issue?

**Comment by cipriancraciun** [comment]
@mblaje Da, cred ca este done.  Daca vrei putem sa il inchidem.
